const memberList = [
    { "name": "Khoa Nguyễn",
      "type": "Project Leader",
      "desc": "Người dẫn dắt và quản lí dự án, lên kế hoạch cũng như phụ trách kĩ thuật...",
      "img": "/team/khoa.jpeg",
      "link": "https://www.facebook.com/yun.khngn",
    },
    { "name": "Đức Cường",
      "type": "Truyền thông",
      "desc": "Quản lí fanpage, làm truyền thông và cập nhật thông tin về dự án...",
      "img": "/team/cuong.jpg",
      "link": "https://www.facebook.com/harrypham.04",
    },
    { "name": "Phan Thảo",
      "type": "Tài chính",
      "desc": "Phụ trách quản lí tài chính, kinh tế và quỹ funding cho dự án...",
      "img": "/team/cat.jpg",
      "link": "https://www.facebook.com/yun.khngn",
    },
    { "name": "Tuấn Anh",
      "type": "Media/Photo",
      "desc": "Chụp ảnh, quay video tư liệu, media sự kiện cho dự án...",
      "img": "/team/tuanbro.jpeg",
      "link": "https://www.facebook.com/meditQuynh69",
    },
    { "name": "Hoàng Sơn",
      "type": "Đối ngoại",
      "desc": "Liên hệ trao đổi với nhà tài trợ và các mạnh thường quân...",
      "img": "/team/son.jpg",
      "link": "https://www.facebook.com/SownLee1105",
    },
    { "name": "Hồng Hiếu",
      "type": "Hậu cần",
      "desc": "Hỗ trợ nhân sự, hậu cần và setup tổ chức sự kiện...",
      "img": "/team/cat.jpg",
      "link": "https://www.facebook.com/SownLee1105",
    },
    { "name": "Lê Hoàng",
      "type": "Hậu cần",
      "desc": "Hỗ trợ nhân sự, hậu cần  và setup tổ chức sự kiện...",
      "img": "/team/hoang.jpg",
      "link": "https://google.com",
    },
]

export default memberList;