export {default as Homepage} from './Homepage'
export {default as About} from './About'
export {default as Pics} from './Pics'
export {default as Fund} from './Fund'
export {default as Poster} from './Poster'
export {default as Mail} from './Mail'